[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "luna-ai-core"
version = "0.1.0"
description = "Luna AI Core POC"
authors = [{name = "Saurabh Tiwari"}]
dependencies = [
"fastapi>=0.115.0",
"uvicorn[standard]>=0.30.0",
"pydantic>=2.9.0",
"pydantic-settings>=2.5.0",
"python-dotenv>=1.0.0"
]
[tool.setuptools.packages.find]
where = ["src"]
